BurgerApp/BurgerApp.App/Controllers/BurgerController.cs
using BurgerApp.Services.Interfaces;
using BurgerApp.ViewModels.BurgerViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.App.Controllers
{
    public class BurgerController : Controller
    {
        private IBurgerService _burgerService;

        public BurgerController(IBurgerService _burgerService)
        {
            this._burgerService = _burgerService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _burgerService.GetBurgersForCards());
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _burgerService.GetBurgerDetails(id));
        }
        
        public async Task<IActionResult> Delete(int id)
        {
            return View(await _burgerService.DeleteBurgerById(id));
        }

        public IActionResult Create()
        {
            BurgerViewModel burgerViewModel = new BurgerViewModel();

            return View(burgerViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Create(BurgerViewModel burgerViewModel)
        {
            await _burgerService.CreateBurger(burgerViewModel);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            BurgerViewModel burgerViewModel = await _burgerService.GetBurgerForEditing(id);

            return View(burgerViewModel);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(BurgerViewModel burgerViewModel)
        {
            await _burgerService.EditBurger(burgerViewModel);

            return RedirectToAction("Index");
        }
    }
}

BurgerApp/BurgerApp.App/Controllers/HomeController.cs
using BurgerApp.DataAccess.Repositories.Interfaces;
using BurgerApp.Services.Interfaces;
using BurgerApp.ViewModels.HomeViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.App.Controllers
{
    public class HomeController : Controller
    {
        private IBurgerService _burgerService;

        public HomeController(ILogger<HomeController> logger, IBurgerService _burgerService)
        {
            this._burgerService = _burgerService;
        }

        public IActionResult Index()
        {
            HomeViewModel homeViewModel = new HomeViewModel();

            homeViewModel.BurgerForPromotion = _burgerService.GetBurgerForPromotion();
            return View(homeViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

    }
}

BurgerApp/BurgerApp.App/Controllers/LocationController.cs
using BurgerApp.Services.Implementations;
using BurgerApp.Services.Interfaces;
using BurgerApp.ViewModels.LocationViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.App.Controllers
{
    public class LocationController : Controller
    {
        private ILocationService _locationService;

        public LocationController(ILocationService _locationService)
        {
            this._locationService = _locationService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _locationService.GetAllLocations());
        }

        public async Task<IActionResult> Delete(int id)
        {
            return View(await _locationService.DeleteLocationById(id));
        }

        public IActionResult Create()
        {
            LocationViewModel locationViewModel = new LocationViewModel();

            return View(locationViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(LocationViewModel locationViewModel)
        {
            await _locationService.CreateLocation(locationViewModel);
            return RedirectToAction("Index");
        }
    }
}

BurgerApp/BurgerApp.App/Controllers/OrderController.cs
using BurgerApp.Services.Interfaces;
using BurgerApp.ViewModels.OrderViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.App.Controllers
{
    public class OrderController : Controller
    {
        private IOrderService _orderService;
        private ILocationService _locationService;
        private IBurgerService _burgerService;

        public OrderController(IOrderService _orderService, ILocationService _locationService, IBurgerService _burgerService)
        {
            this._orderService = _orderService;
            this._locationService = _locationService;
            this._burgerService = _burgerService;

        }
        public async Task<IActionResult> Index()
        {
            return View(await _orderService.GetAllOrders());
        }

        public async Task<IActionResult> Delete(int id)
        {
            return View(await _orderService.DeleteOrderById(id));
        }

        public async Task<IActionResult> Create()
        {
            OrderViewModel orderViewModel = new OrderViewModel();
            ViewBag.Locations = await _locationService.GetLocationsForDropdown();
            ViewBag.Burgers = await _burgerService.GetBurgersForDropdown();

            return View(orderViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderViewModel orderViewModel)
        {
            await _orderService.CreateOrder(orderViewModel);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            OrderViewModel orderViewModel = await _orderService.GetOrderForEditing(id);
            ViewBag.Locations = await _locationService.GetLocationsForDropdown();
            ViewBag.Burgers = await _burgerService.GetBurgersForDropdown();

            return View(orderViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(OrderViewModel orderViewModel)
        {
            await _orderService.EditOrder(orderViewModel);

            return RedirectToAction("Index");
        }
    }
}

BurgerApp/BurgerApp.App/Views/Burger/Create.cshtml
@model BurgerViewModel

<h3>Create new burger</h3>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="Name" class="custom-control-label"></label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Price" class="custom-control-label"></label>
                <input type="double" asp-for="Price" />
            </div>
            <div class="form-group">
                <label asp-for="IsVegetarian" class="custom-control-label"></label>
                <input type="checkbox" asp-for="IsVegetarian" />
            </div>
            <div class="form-group">
                <label asp-for="IsVegan" class="custom-control-label"></label>
                <input type="checkbox" asp-for="IsVegan" />
            </div>
            <div class="form-group">
                <label asp-for="IsOnPromotion" class="custom-control-label"></label>
                <input type="checkbox" asp-for="IsOnPromotion" />
            </div>
            <div class="form-group">
                <label asp-for="HasFries" class="custom-control-label"></label>
                <input type="checkbox" asp-for="HasFries" />
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="custom-control-label"></label>
                <input type="text" asp-for="ImageUrl" class="form-control" />
            </div>
            <button type="submit" class="btn btn-outline-success">Create</button>
        </form>
    </div>
</div>

BurgerApp/BurgerApp.App/Views/Burger/Delete.cshtml
<h2>The burger has been deleted!</h2>

<br />
<a class="btn btn-warning" asp-area="" asp-controller="Burger" asp-action="Index">Go back to the burgers</a>

BurgerApp/BurgerApp.App/Views/Burger/Details.cshtml
@model BurgerDetailsViewModel

<div class="text-center">
    <h2 class="display-4">Burger Details</h2>
</div>
<br />

@{
    double priceWithFriesOnly = Model.Price + 0.30;
    double priceOnPromotionWithFries = Model.Price - 0.50;
    double priceOnPromotionOnly = Model.Price - 0.80;
}

<div class="card">
    <div class="card-body card-body-details">
        <img class="card-img-top card-img" src="@Model.ImageUrl" alt="Card image cap">
        <div class="burger-details">
            <h5 class="card-title card-title-name">Name: @Model.Name</h5>

            <h5 class="card-title card-title-name">Is Vegetarian: @(Model.IsVegetarian ? "✓" : "✗")</h5>
            <h5 class="card-title card-title-name">Is Vegan: @(Model.IsVegan ? "✓" : "✗")</h5>
            <h5 class="card-title card-title-name">Fries: @(Model.HasFries ? "✓" : "✗")</h5>
            <h5 class="card-title card-title-name">On Promotion: @(Model.IsOnPromotion ? "✓" : "✗")</h5>

            <br />
            <br />

           

            @{
                var price = Model.HasFries
                ? (Model.IsOnPromotion ? priceOnPromotionWithFries : priceWithFriesOnly)
                : (Model.IsOnPromotion ? priceOnPromotionOnly : Model.Price);
            }

            <h5 class="card-title card-title-name">Price: @(price.ToString("0.00"))$</h5>

        </div>
    </div>
</div>
<br />

BurgerApp/BurgerApp.App/Views/Burger/Edit.cshtml
@model BurgerViewModel

<h3>Edit @Model.Name</h3>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="custom-control-label"></label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Price" class="custom-control-label"></label>
                <input type="double" asp-for="Price" />
            </div>
            <div class="form-group">
                <label asp-for="IsVegetarian" class="custom-control-label"></label>
                <input type="checkbox" asp-for="IsVegetarian" />
            </div>
            <div class="form-group">
                <label asp-for="IsVegan" class="custom-control-label"></label>
                <input type="checkbox" asp-for="IsVegan" />
            </div>
            <div class="form-group">
                <label asp-for="IsOnPromotion" class="custom-control-label"></label>
                <input type="checkbox" asp-for="IsOnPromotion" />
            </div>
            <div class="form-group">
                <label asp-for="HasFries" class="custom-control-label"></label>
                <input type="checkbox" asp-for="HasFries" />
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="custom-control-label"></label>
                <input type="text" asp-for="ImageUrl" class="form-control" />
            </div>
            <button type="submit" class="btn btn-outline-success">Submit</button>
        </form>
    </div>
</div>

BurgerApp/BurgerApp.App/Views/Burger/Index.cshtml
@model List<BurgerListViewModel>

<div class="card-container">
    
    @foreach (var burger in @Model)
    {
        
        double priceWithFriesOnly = burger.Price + 0.30;
        double priceOnPromotionWithFries = burger.Price - 0.50;
        double priceOnPromotionOnly = burger.Price - 0.80;
    
        
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="@burger.ImageUrl" alt="Card image cap" height="250px">
            <div class="card-body">
                <h5 class="card-title">@burger.Name</h5>

                <p class="card-text">
                    @(
                        @burger.HasFries
                        ? (@burger.IsOnPromotion ? priceOnPromotionWithFries : priceWithFriesOnly)
                        : (@burger.IsOnPromotion ? priceOnPromotionOnly : @burger.Price)
                        .ToString("0.00"))$
                </p>


            </div>
            <br />
            <a type="button" class="btn btn-primary" asp-action="Details" asp-route-id="@burger.Id">Details</a>
            <br />
            <a type="button" class="btn btn-warning" asp-action="Edit" asp-route-id="@burger.Id">Edit</a>
            <br />
            <a type="button" class="btn btn-danger" asp-action="Delete" asp-route-id="@burger.Id">Delete</a>

        </div>
    }
</div>
<br />

<div class="HomeIndexBtns">
    <a class="btn btn-warning btnHomePage" asp-area="" asp-controller="Home" asp-action="Index">Home page</a>
    <br />
    <br />
    <a class="btn btn-secondary btnCreateBurger" asp-area="" asp-controller="Burger" asp-action="Create">Add Burger</a>
</div>

BurgerApp/BurgerApp.App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model HomeViewModel

<div class="jumbotron">
    <h1>Welcome to our burger app!</h1>
    <h3>Today on promotion: @Model.BurgerForPromotion</h3>
</div>

BurgerApp/BurgerApp.App/Views/Location/Create.cshtml
@model LocationViewModel

<h3>Add new Location</h3>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="Name" class="custom-control-label"></label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Address" class="custom-control-label"></label>
                <input type="text" asp-for="Address" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="OpensAt" class="custom-control-label"></label>
                <input type="text" asp-for="OpensAt" class="form-control" placeholder="ex. 09:00"/>
            </div>
            <div class="form-group">
                <label asp-for="ClosesAt" class="custom-control-label"></label>
                <input type="text" asp-for="ClosesAt" class="form-control" placeholder="ex. 22:00"/>
            </div>
            <button type="submit" class="btn btn-outline-success">Add</button>
        </form>
    </div>
</div>

BurgerApp/BurgerApp.App/Views/Location/Delete.cshtml
<h2>The location has been deleted!</h2>

<br />
<a class="btn btn-warning" asp-area="" asp-controller="Location" asp-action="Index">Go back to the Locations</a>

BurgerApp/BurgerApp.App/Views/Location/Index.cshtml
@model List<LocationListViewModel>

<h2>Locations:</h2>
<br />

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Opens At</th>
            <th>Closes At</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var location in Model)
        {
            <tr>
                <td>@location.Name</td>
                <td>@location.Address</td>
                <td>@location.OpensAt AM</td>
                <td>@location.ClosesAt PM</td>
                <td><a type="button" class="btn btn-danger" asp-action="Delete" asp-route-id="@location.Id">Delete</a></td>

            </tr>
        }
    </tbody>
</table>

<a type="button" class="btn btn-secondary" asp-action="Create" asp-route-id="Model.Id">Add Location</a>

BurgerApp/BurgerApp.App/Views/Order/Create.cshtml
@model OrderViewModel

<h3>Create new order:</h3>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="FullName" class="custom-control-label"></label>
                <input type="text" asp-for="FullName" class="form-control" placeholder="ex. John Doe" />
            </div>
            <div class="form-group">
                <label asp-for="Address" class="custom-control-label"></label>
                <input type="text" asp-for="Address" />
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" asp-items="@(new SelectList(ViewBag.Locations, "Id", "Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="BurgerId" class="control-label"></label>
                <select asp-for="BurgerId" asp-items="@(new SelectList(ViewBag.Burgers, "Id", "Name"))" class="selectBurgers"></select>
            </div>

            <div class="form-group">
                <label asp-for="IsDelivered" class="custom-control-label"></label>
                <input type="checkbox" asp-for="IsDelivered" />
            </div> 
            <button type="submit" class="btn btn-outline-success">Create</button>
        </form>
    </div>
</div>

BurgerApp/BurgerApp.App/Views/Order/Delete.cshtml
<h2>The burger has been deleted!</h2>

<br />
<a class="btn btn-warning" asp-area="" asp-controller="Order" asp-action="Index">Go back to the orders</a>

BurgerApp/BurgerApp.App/Views/Order/Edit.cshtml
@model OrderViewModel

<h3>Edit Order</h3>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FullName" class="custom-control-label"></label>
                <input type="text" asp-for="FullName" class="form-control" placeholder="ex. John Doe" />
            </div>
            <div class="form-group">
                <label asp-for="Address" class="custom-control-label"></label>
                <input type="text" asp-for="Address" />
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" asp-items="@(new SelectList(ViewBag.Locations, "Id", "Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="BurgerId" class="control-label"></label>
                <select asp-for="BurgerId" asp-items="@(new SelectList(ViewBag.Burgers, "Id", "Name"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="IsDelivered" class="custom-control-label"></label>
                <input type="checkbox" asp-for="IsDelivered" />
            </div>
            <button type="submit" class="btn btn-outline-success">Submit</button>
        </form>
    </div>
</div>

BurgerApp/BurgerApp.App/Views/Order/Index.cshtml
@model List<OrderListViewModel>

<div class="card-container">
    @{
        int orderNumber = 1;
    }
    @foreach (var order in Model)
    {
        <div class="card" style="width: 18rem;">
            <h3 class="orderNumber">Order: @orderNumber</h3>

            <div class="card-body">

                <h5 class="card-title">@order.FullName</h5>
                <p class="card-text">@order.Address</p>

                <p class="@(order.IsDelivered ? "text-success" : "text-danger")">
                    @(order.IsDelivered ? "Delivered" : "Not Delivered")
                </p>

                <br />
                <div class="OrderPartialBtns">
                    <a type="button" class="btn btn-danger" asp-action="Delete" asp-route-id="@order.Id">Delete</a>
                    <br />
                    <a type="button" class="btn btn-warning" asp-action="Edit" asp-route-id="@order.Id">Edit Order</a>
                </div>

            </div>
            <br />
        </div>
        orderNumber++;
    }
</div>
<br />
<div class="OrderIndexBtns">
    <a class="btn btn-warning" asp-area="" asp-controller="Home" asp-action="Index">Home page</a>
    <br />
    <br />
    <a class="btn btn-secondary" asp-area="" asp-controller="Order" asp-action="Create">Create order</a>
</div>

BurgerApp/BurgerApp.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BurgerApp.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BurgerApp.App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BurgerApp.App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Burger" asp-action="Index">Burgers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="Index">Locations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BurgerApp.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>