LibraryApp/LibraryApp.App/Controllers/AuthorController.cs
using LibraryApp.Services.Interfaces;
using LibraryApp.ViewModels.AuthorViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LibraryApp.App.Controllers
{
    public class AuthorController : Controller
    {
        private IAuthorService _authorService;

        public AuthorController(IAuthorService _authorService)
        {
            this._authorService = _authorService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _authorService.GetAllAuthors());
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _authorService.GetAuthorDetails(id));
        }

        public async Task<IActionResult> Delete(int id)
        {
            return View(await _authorService.DeleteAuthorById(id));
        }

        public IActionResult Create()
        {
            AuthorViewModel authorViewModel = new AuthorViewModel();
            return View(authorViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuthorViewModel authorViewModel)
        {
            await _authorService.AddAuthor(authorViewModel);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            AuthorViewModel authorViewModel = await _authorService.GetAuthorForEditing(id);
            return View(authorViewModel);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(AuthorViewModel authorViewModel)
        {
            await _authorService.EditAuthor(authorViewModel);
            return RedirectToAction("Index");
        }
    }
}

LibraryApp/LibraryApp.App/Controllers/BookController.cs
using LibraryApp.Services.Interfaces;
using LibraryApp.ViewModels.BookViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LibraryApp.App.Controllers
{
    public class BookController : Controller
    {
        private IBookService _bookService;
        private IAuthorService _authorService;

        public BookController(IBookService _bookService, IAuthorService _authorService)
        {
            this._bookService = _bookService;
            this._authorService = _authorService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _bookService.GetAllBooks());
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _bookService.GetBookDetails(id));
        }

        public async Task<IActionResult> Delete(int id)
        {
            return View(await _bookService.DeleteBookById(id));
        }

        public async Task<IActionResult> Create()
        {
            BookViewModel bookViewModel = new BookViewModel();
            ViewBag.Authors = await _authorService.GetAuthorsForDropdown();

            return View(bookViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(BookViewModel bookViewModel)
        {
            await _bookService.AddBook(bookViewModel);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int id)
        {
            BookViewModel bookViewModel = await _bookService.GetBookForEditing(id);
            ViewBag.Authors = await _authorService.GetAuthorsForDropdown();

            return View(bookViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BookViewModel bookViewModel)
        {
            await _bookService.EditBook(bookViewModel);
            return RedirectToAction("Index");
        }
    }
}

LibraryApp/LibraryApp.App/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace LibraryApp.App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

LibraryApp/LibraryApp.App/Controllers/MemberController.cs
using LibraryApp.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LibraryApp.App.Controllers
{
    public class MemberController : Controller
    {
        private IMemberService _memberService;

        public MemberController(IMemberService _memberService)
        {
            this._memberService = _memberService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _memberService.GetAllMembers());
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _memberService.GetMemberDetails(id));
        }
    }
}

LibraryApp/LibraryApp.App/Views/Author/Create.cshtml
@model AuthorViewModel

<h3>Add Author</h3>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="FirstName" class="custom-control-label"></label>
                <input type="text" asp-for="FirstName" />
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="custom-control-label"></label>
                <input type="text" asp-for="LastName" />
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="custom-control-label"></label>
                <input type="text" asp-for="ImageUrl" />
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="custom-control-label"></label>
                <input type="text" asp-for="Nationality" />
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="custom-control-label"></label>
                <input type="text" asp-for="BirthDate" />
            </div>
            <div class="form-group">
                <label asp-for="Biography" class="custom-control-label"></label>
                <input type="text" asp-for="Biography" />
            </div>
            <div class="form-group">
                <label asp-for="BooksPublished" class="custom-control-label"></label>
                <input type="double" asp-for="BooksPublished" />
            </div>
            <button type="submit" class="btn btn-outline-success">Create</button>
        </form>
    </div>
</div>

LibraryApp/LibraryApp.App/Views/Author/Delete.cshtml
<h2>The author has been deleted!</h2>

<br />
<a class="btn btn-warning" asp-area="" asp-controller="Author" asp-action="Index">Go back to the Authors</a>

LibraryApp/LibraryApp.App/Views/Author/Details.cshtml
@model AuthorDetailsViewModel

<div class="text-center">
    <h2 class="display-4">About @Model.FirstName @Model.LastName</h2>
</div>
<br />

<div class="card">
    <div class="card-body card-body-details">
        <img class="card-img-top card-img" src="@Model.ImageUrl" alt="Card image cap">
        <div class="author-details">
            <p class="card-title card-title-name"><strong>Full Name:</strong> @Model.FirstName @Model.LastName</p>
            <p class="card-title card-title-name"><strong>Nationality: </strong>@Model.Nationality</p>
            <p class="card-title card-title-name"><strong>Books Published: </strong>@Model.BooksPublished</p>
            <p class="card-title card-title-name"><strong>Birth Date: </strong>@Model.BirthDate</p>
            <p class="card-title card-title-name"><strong>Biography: </strong>@Model.Biography</p>
        </div>
    </div>
</div>
<br />

LibraryApp/LibraryApp.App/Views/Author/Edit.cshtml
@model AuthorViewModel

<h3> Edit @Model.FirstName @Model.LastName</h3>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="custom-control-label"></label>
                <input type="text" asp-for="FirstName" />
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="custom-control-label"></label>
                <input type="text" asp-for="LastName" />
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="custom-control-label"></label>
                <input type="text" asp-for="ImageUrl" />
            </div>
            <div class="form-group">
                <label asp-for="Nationality" class="custom-control-label"></label>
                <input type="text" asp-for="Nationality" />
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="custom-control-label"></label>
                <input type="text" asp-for="BirthDate" />
            </div>
            <div class="form-group">
                <label asp-for="Biography" class="custom-control-label"></label>
                <input type="text" asp-for="Biography" />
            </div>
            <div class="form-group">
                <label asp-for="BooksPublished" class="custom-control-label"></label>
                <input type="double" asp-for="BooksPublished" />
            </div>
            <button type="submit" class="btn btn-outline-success">Save</button>
        </form>
    </div>
</div>

LibraryApp/LibraryApp.App/Views/Author/Index.cshtml
@model List<AuthorListViewModel>

<br />

<div class="row">
    @foreach (var author in Model)
    {
        <div class="col-md-4">
            <div class="card mb-4">
                <img class="card-img-top authorsImg" src="@author.ImageUrl" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title authorFullName">@author.FirstName @author.LastName</h5>
                    <p class="card-text authorNationality"><strong>Nationality:</strong> @author.Nationality</p>
                    <a type="button" class="btn btn-link" asp-action="Details" asp-route-id="@author.Id">View Details</a>
                    <a type="button" class="btn btn-link" asp-action="Edit" asp-route-id="@author.Id">Edit</a>
                    <a type="button" class="btn btn-link" asp-action="Delete" asp-route-id="@author.Id">Delete</a>
                </div>
            </div>
        </div>
    }
</div>

<a class="btn btn-secondary" asp-area="" asp-controller="Author" asp-action="Create">Add Author</a>

LibraryApp/LibraryApp.App/Views/Book/Create.cshtml
@model BookViewModel

<h3>Add Book</h3>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="Title" class="custom-control-label"></label>
                <input type="text" asp-for="Title" />
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" asp-items="@(new SelectList(ViewBag.Authors, "Id", "FullName"))" class="selectAuthor"></select>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="custom-control-label"></label>
                <input type="text" asp-for="ImageUrl" />
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="custom-control-label"></label>
                <input type="text" asp-for="ISBN" />
            </div>
            <div class="form-group">
                <label asp-for="Synopsis" class="custom-control-label"></label>
                <textarea asp-for="Synopsis" rows="4" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select class="form-control" asp-for="Genre" asp-items="Html.GetEnumSelectList<Genre>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="PublicationDate" class="custom-control-label"></label>
                <input type="date" asp-for="PublicationDate" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
            </div>

            <button type="submit" class="btn btn-outline-success">Create</button>
        </form>
    </div>
</div>

LibraryApp/LibraryApp.App/Views/Book/Delete.cshtml
<h2>The book has been deleted!</h2>

<br />
<a class="btn btn-warning" asp-area="" asp-controller="Book" asp-action="Index">Back to the Books</a>

LibraryApp/LibraryApp.App/Views/Book/Details.cshtml
@model BookDetailsViewModel

<div class="text-center">
    <h2 class="display-4">About @Model.Title</h2>
</div>
<br />

<div class="card">
    <div class="card-body card-body-details">
        <img class="card-img-top card-img-bookDetails" src="@Model.ImageUrl" alt="Card image cap">
        <div class="book-details">
            <p class="card-title card-title-name"><strong>Title:</strong> "@Model.Title"</p>
            <p class="card-title card-title-name"><strong>Published by:</strong> @Model.AuthorFullName</p>
            <p class="card-title card-title-name"><strong>Genre: </strong>@Model.Genre</p>
            <p class="card-title card-title-name"><strong>ISBN: </strong>@Model.ISBN</p>
            <p class="card-title card-title-name"><strong>Publication Date: </strong>@Model.PublicationDate.ToString("dd/MM/yyyy")</p>
            <p class="card-title card-title-name"><strong>Synopsis: </strong>@Model.Synopsis</p>
        </div>
    </div>
</div>
<br />

LibraryApp/LibraryApp.App/Views/Book/Edit.cshtml
@model BookViewModel

<h3>Edit @Model.Title</h3>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="custom-control-label"></label>
                <input type="text" asp-for="Title" />
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" asp-items="@(new SelectList(ViewBag.Authors, "Id", "FullName"))" class="selectAuthor"></select>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="custom-control-label"></label>
                <input type="text" asp-for="ImageUrl" />
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="custom-control-label"></label>
                <input type="text" asp-for="ISBN" />
            </div>
            <div class="form-group">
                <label asp-for="Synopsis" class="custom-control-label"></label>
                <textarea asp-for="Synopsis" rows="4" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select class="form-control" asp-for="Genre" asp-items="Html.GetEnumSelectList<Genre>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="PublicationDate" class="custom-control-label"></label>
                <input type="date" asp-for="PublicationDate" value="@Model.PublicationDate.ToString("yyyy-MM-dd")" />
            </div>

            <button type="submit" class="btn btn-outline-success">Save</button>
        </form>
    </div>
</div>

LibraryApp/LibraryApp.App/Views/Book/Index.cshtml
@model List<BookListViewModel>

<br />
<div class="row">
    @foreach (var book in Model)
    {
        <div class="card border-success mb-3" style="max-width: 18rem; margin-left: 10px;">
            <img class="card-img-top card-img-bookIndex" src="@book.ImageUrl" alt="Card image cap">
            <div class="card-body text-success">
                <h5 class="card-title">@book.Title</h5>
                <button type="button" class="btn"><a asp-action="Details" asp-route-id="@book.Id">Details</a></button>
                <button type="button" class="btn"><a asp-action="Edit" asp-route-id="@book.Id">Edit</a></button>
                <button type="button" class="btn"><a asp-action="Delete" asp-route-id="@book.Id">Delete</a></button>
            </div>
        </div>
    }
</div>
<a class="btn btn-secondary" asp-area="" asp-controller="Book" asp-action="Create">Add Book</a>

LibraryApp/LibraryApp.App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the LibrarianPro!</h1>
</div>

LibraryApp/LibraryApp.App/Views/Member/Details.cshtml
@model MemberDetailsViewModel

<div class="card">
    <div class="card-body">
        <div class="member-details">
            <p class="card-title card-title-name"><strong>Name:</strong> @Model.Name</p>
            <p class="card-title card-title-name"><strong>Membership ID: </strong>@Model.MembershipID</p>
            <p class="card-title card-title-name"><strong>Phone Number: </strong>@Model.PhoneNumber</p>
            <p class="card-title card-title-name"><strong>Membership Status: </strong>@Model.MembershipStatus</p>
        </div>
    </div>
</div>
<br />

LibraryApp/LibraryApp.App/Views/Member/Index.cshtml
@model List<MemberListViewModel>

<div class="row">
    @foreach (var member in Model)
    {
        <div class="col-md-4 mb-3">
            <div class="card border-success">
                <div class="card-body text-success">
                    <h5 class="card-title">Name: @member.Name</h5>
                    <h5 class="card-title">Phone number: @member.PhoneNumber</h5>
                    <h5 class="card-title">Membership Status: @member.MembershipStatus</h5>
                    <button type="button" class="btn"><a asp-action="Details" asp-route-id="@member.Id">Details</a></button>
                </div>
            </div>
        </div>
    }
</div>

LibraryApp/LibraryApp.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibrarianPro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryApp.App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibrarianPro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Members</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LibraryApp.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>